# Generated by Django 5.1.1 on 2025-06-05 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=50, null=True)),
                ('call_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, default='message', max_length=30, null=True)),
                ('arguments', models.JSONField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
