# Generated by Django 5.1.1 on 2025-06-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='customer_profile',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
