# Generated by Django 5.1.1 on 2024-09-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customermodel_address_conversationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
