# Generated by Django 5.1.1 on 2024-09-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationhistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customermodel'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
