# Generated by Django 5.1.3 on 2024-11-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_conversationhistory_tool_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='tool_calls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
